BEGIN;

SET LOCAL lock_timeout = '3s';
SET LOCAL statement_timeout = '30s';

SELECT pg_advisory_xact_lock(7356507374803211041);

DO $storecalc_role_preflight$
DECLARE
    migration_owner_role text := current_setting('storecalc.migration_owner_role', true);
    web_role text := current_setting('storecalc.web_role', true);
    worker_role text := current_setting('storecalc.worker_role', true);
    backup_role text := current_setting('storecalc.backup_role', true);
    configured_roles text[];
    source_role text;
    target_role text;
    distinct_role_count integer;
BEGIN
    configured_roles := ARRAY[
        migration_owner_role,
        web_role,
        worker_role,
        backup_role
    ];

    IF array_position(configured_roles, NULL) IS NOT NULL
       OR array_position(configured_roles, '') IS NOT NULL THEN
        RAISE EXCEPTION 'storecalc_role_config_missing'
            USING ERRCODE = '22023';
    END IF;

    IF lower('public') = ANY (
        ARRAY(
            SELECT lower(role_name)
            FROM unnest(configured_roles) AS role_name
        )
    ) THEN
        RAISE EXCEPTION 'storecalc_public_role_forbidden'
            USING ERRCODE = '22023';
    END IF;

    SELECT count(DISTINCT role_name)
    INTO distinct_role_count
    FROM unnest(configured_roles) AS role_name;

    IF distinct_role_count <> 4 THEN
        RAISE EXCEPTION 'storecalc_roles_must_be_distinct'
            USING ERRCODE = '22023';
    END IF;

    IF migration_owner_role <> current_user THEN
        RAISE EXCEPTION 'storecalc_migration_owner_mismatch'
            USING ERRCODE = '42501';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM unnest(configured_roles) AS configured(role_name)
        LEFT JOIN pg_roles AS roles
          ON roles.rolname = configured.role_name
        WHERE roles.oid IS NULL
    ) THEN
        RAISE EXCEPTION 'storecalc_configured_role_missing'
            USING ERRCODE = '42704';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM pg_roles
        WHERE rolname = ANY (configured_roles)
          AND (
              rolsuper
              OR rolcreaterole
              OR rolcreatedb
              OR rolreplication
              OR rolbypassrls
          )
    ) THEN
        RAISE EXCEPTION 'storecalc_configured_role_is_overprivileged'
            USING ERRCODE = '42501';
    END IF;

    IF NOT has_database_privilege(
        migration_owner_role,
        current_database(),
        'CREATE'
    ) THEN
        RAISE EXCEPTION 'storecalc_migration_owner_lacks_database_create'
            USING ERRCODE = '42501';
    END IF;

    IF has_database_privilege(web_role, current_database(), 'CREATE')
       OR has_database_privilege(worker_role, current_database(), 'CREATE')
       OR has_database_privilege(backup_role, current_database(), 'CREATE') THEN
        RAISE EXCEPTION 'storecalc_runtime_role_has_database_create'
            USING ERRCODE = '42501';
    END IF;

    FOREACH source_role IN ARRAY configured_roles LOOP
        FOREACH target_role IN ARRAY configured_roles LOOP
            IF source_role <> target_role
               AND pg_has_role(source_role, target_role, 'MEMBER') THEN
                RAISE EXCEPTION 'storecalc_configured_roles_must_not_inherit_each_other'
                    USING ERRCODE = '42501';
            END IF;
        END LOOP;
    END LOOP;

    IF to_regnamespace('storecalc') IS NOT NULL THEN
        RAISE EXCEPTION 'storecalc_schema_already_exists'
            USING ERRCODE = '42P06';
    END IF;
END
$storecalc_role_preflight$;

CREATE SCHEMA storecalc AUTHORIZATION CURRENT_USER;

CREATE TABLE storecalc.schema_capabilities (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    capability_key text NOT NULL,
    schema_version integer NOT NULL,
    is_available boolean NOT NULL DEFAULT false,
    verified_at timestamptz,
    migration_key text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    CONSTRAINT schema_capabilities_pkey
        PRIMARY KEY (id),
    CONSTRAINT schema_capabilities_capability_key_key
        UNIQUE (capability_key),
    CONSTRAINT schema_capabilities_capability_key_format_check
        CHECK (
            char_length(capability_key) BETWEEN 1 AND 64
            AND octet_length(capability_key) <= 64
            AND capability_key ~ '^[a-z][a-z0-9]*(\.[a-z][a-z0-9_]*)*$'
        ),
    CONSTRAINT schema_capabilities_schema_version_check
        CHECK (schema_version >= 0),
    CONSTRAINT schema_capabilities_migration_key_format_check
        CHECK (
            char_length(migration_key) BETWEEN 6 AND 64
            AND octet_length(migration_key) <= 64
            AND migration_key ~ '^[0-9]{4}_[a-z][a-z0-9_]*$'
        ),
    CONSTRAINT schema_capabilities_available_verified_check
        CHECK (NOT is_available OR verified_at IS NOT NULL)
);

INSERT INTO storecalc.schema_capabilities (
    capability_key,
    schema_version,
    is_available,
    verified_at,
    migration_key
)
VALUES
    (
        'schema.foundation',
        1,
        true,
        transaction_timestamp(),
        '0001_schema_foundation'
    ),
    ('public.directory', 0, false, NULL, '0001_schema_foundation'),
    ('anonymous.calculation', 0, false, NULL, '0001_schema_foundation'),
    ('saved.orders', 0, false, NULL, '0001_schema_foundation'),
    ('public.contribution', 0, false, NULL, '0001_schema_foundation'),
    ('evidence.upload', 0, false, NULL, '0001_schema_foundation'),
    ('owner.support', 0, false, NULL, '0001_schema_foundation'),
    ('scoped.profiles', 0, false, NULL, '0001_schema_foundation');

REVOKE ALL ON SCHEMA storecalc FROM PUBLIC;
REVOKE ALL ON TABLE storecalc.schema_capabilities FROM PUBLIC;
REVOKE ALL ON SEQUENCE storecalc.schema_capabilities_id_seq FROM PUBLIC;

DO $storecalc_grants$
DECLARE
    web_role text := current_setting('storecalc.web_role');
    worker_role text := current_setting('storecalc.worker_role');
    backup_role text := current_setting('storecalc.backup_role');
    grantee text;
BEGIN
    FOREACH grantee IN ARRAY ARRAY[web_role, worker_role, backup_role] LOOP
        EXECUTE format(
            'GRANT USAGE ON SCHEMA storecalc TO %I',
            grantee
        );
        EXECUTE format(
            'GRANT SELECT ON TABLE storecalc.schema_capabilities TO %I',
            grantee
        );
    END LOOP;

    EXECUTE format(
        'GRANT SELECT ON SEQUENCE storecalc.schema_capabilities_id_seq TO %I',
        backup_role
    );
END
$storecalc_grants$;

DO $storecalc_postflight$
DECLARE
    migration_owner_role text := current_setting('storecalc.migration_owner_role');
    web_role text := current_setting('storecalc.web_role');
    worker_role text := current_setting('storecalc.worker_role');
    backup_role text := current_setting('storecalc.backup_role');
    relation_owner text;
BEGIN
    SELECT pg_get_userbyid(nspowner)
    INTO relation_owner
    FROM pg_namespace
    WHERE nspname = 'storecalc';

    IF relation_owner IS DISTINCT FROM migration_owner_role THEN
        RAISE EXCEPTION 'storecalc_schema_owner_mismatch';
    END IF;

    SELECT tableowner
    INTO relation_owner
    FROM pg_tables
    WHERE schemaname = 'storecalc'
      AND tablename = 'schema_capabilities';

    IF relation_owner IS DISTINCT FROM migration_owner_role THEN
        RAISE EXCEPTION 'storecalc_table_owner_mismatch';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM pg_namespace AS namespaces,
             LATERAL aclexplode(COALESCE(namespaces.nspacl, acldefault('n', namespaces.nspowner))) AS acl
        WHERE namespaces.nspname = 'storecalc'
          AND acl.grantee = 0
    ) THEN
        RAISE EXCEPTION 'storecalc_public_schema_grant_detected';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM pg_class AS relations,
             LATERAL aclexplode(COALESCE(relations.relacl, acldefault('r', relations.relowner))) AS acl
        WHERE relations.oid = 'storecalc.schema_capabilities'::regclass
          AND acl.grantee = 0
    ) THEN
        RAISE EXCEPTION 'storecalc_public_table_grant_detected';
    END IF;

    IF NOT has_schema_privilege(web_role, 'storecalc', 'USAGE')
       OR has_schema_privilege(web_role, 'storecalc', 'CREATE')
       OR NOT has_schema_privilege(worker_role, 'storecalc', 'USAGE')
       OR has_schema_privilege(worker_role, 'storecalc', 'CREATE')
       OR NOT has_schema_privilege(backup_role, 'storecalc', 'USAGE')
       OR has_schema_privilege(backup_role, 'storecalc', 'CREATE') THEN
        RAISE EXCEPTION 'storecalc_schema_grant_mismatch';
    END IF;

    IF NOT has_table_privilege(web_role, 'storecalc.schema_capabilities', 'SELECT')
       OR has_table_privilege(web_role, 'storecalc.schema_capabilities', 'INSERT')
       OR has_table_privilege(web_role, 'storecalc.schema_capabilities', 'UPDATE')
       OR has_table_privilege(web_role, 'storecalc.schema_capabilities', 'DELETE')
       OR NOT has_table_privilege(worker_role, 'storecalc.schema_capabilities', 'SELECT')
       OR has_table_privilege(worker_role, 'storecalc.schema_capabilities', 'INSERT')
       OR has_table_privilege(worker_role, 'storecalc.schema_capabilities', 'UPDATE')
       OR has_table_privilege(worker_role, 'storecalc.schema_capabilities', 'DELETE')
       OR NOT has_table_privilege(backup_role, 'storecalc.schema_capabilities', 'SELECT')
       OR has_table_privilege(backup_role, 'storecalc.schema_capabilities', 'INSERT')
       OR has_table_privilege(backup_role, 'storecalc.schema_capabilities', 'UPDATE')
       OR has_table_privilege(backup_role, 'storecalc.schema_capabilities', 'DELETE') THEN
        RAISE EXCEPTION 'storecalc_table_grant_mismatch';
    END IF;

    IF has_sequence_privilege(web_role, 'storecalc.schema_capabilities_id_seq', 'SELECT')
       OR has_sequence_privilege(web_role, 'storecalc.schema_capabilities_id_seq', 'USAGE')
       OR has_sequence_privilege(worker_role, 'storecalc.schema_capabilities_id_seq', 'SELECT')
       OR has_sequence_privilege(worker_role, 'storecalc.schema_capabilities_id_seq', 'USAGE')
       OR NOT has_sequence_privilege(backup_role, 'storecalc.schema_capabilities_id_seq', 'SELECT')
       OR has_sequence_privilege(backup_role, 'storecalc.schema_capabilities_id_seq', 'USAGE')
       OR has_sequence_privilege(backup_role, 'storecalc.schema_capabilities_id_seq', 'UPDATE') THEN
        RAISE EXCEPTION 'storecalc_sequence_grant_mismatch';
    END IF;

    IF (SELECT count(*) FROM storecalc.schema_capabilities) <> 8
       OR (SELECT count(*) FROM storecalc.schema_capabilities WHERE is_available) <> 1
       OR NOT EXISTS (
           SELECT 1
           FROM storecalc.schema_capabilities
           WHERE capability_key = 'schema.foundation'
             AND schema_version = 1
             AND is_available
             AND verified_at IS NOT NULL
             AND migration_key = '0001_schema_foundation'
       ) THEN
        RAISE EXCEPTION 'storecalc_capability_seed_mismatch';
    END IF;
END
$storecalc_postflight$;

COMMIT;
