import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { fileURLToPath } from "node:url";
import path from "node:path";
import pg from "pg";

import {
  resolvePublicCatalogVersion,
  StoreCalcCatalogResolutionError,
} from "../src/storecalc/catalog/resolutionService.js";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const DATABASE_NAME = "storecalc_migration_test";
const ROLE_SETTINGS = {
  migration_owner_role: "storecalc_test_migration",
  web_role: "storecalc_test_web",
  worker_role: "storecalc_test_worker",
  backup_role: "storecalc_test_backup",
};
const OUTSIDER_ROLE = "storecalc_test_outsider";
const ALL_TEST_ROLES = [...Object.values(ROLE_SETTINGS), OUTSIDER_ROLE];
const MIGRATIONS = [
  "0001_schema_foundation",
  "0002_directory_lineage",
  "0003_program_assignments",
  "0004_template_identity",
  "0005_template_versions",
  "0006_version_content",
  "0007_buckets",
  "0008_tax_rules",
  "0009_constraints",
  "0010_warnings",
  "0011_source_evidence",
  "0012_catalog_publication_applicability",
];
const REQUIRED_CAPABILITIES = [
  "money.minor_units.v1",
  "quantity.bounded_integer.v1",
];

function quoteIdentifier(value) {
  assert.match(value, /^[a-z][a-z0-9_]*$/);
  return `"${value}"`;
}

function assertDisposableTarget() {
  assert.equal(
    process.env.STORECALC_DB_TEST_ALLOW,
    "1",
    "STORECALC_DB_TEST_ALLOW=1 is required",
  );
  const connectionString = process.env.STORECALC_TEST_DATABASE_URL;
  assert.ok(connectionString, "STORECALC_TEST_DATABASE_URL is required");
  const target = new URL(connectionString);
  assert.ok(
    ["127.0.0.1", "localhost", "::1"].includes(target.hostname),
    "database tests may target only loopback",
  );
  assert.equal(target.pathname, `/${DATABASE_NAME}`);
  return connectionString;
}

async function resetRole(client) {
  await client.query("ROLLBACK").catch(() => null);
  await client.query("RESET ROLE").catch(() => null);
}

async function configureRoles(client) {
  for (const [setting, value] of Object.entries(ROLE_SETTINGS)) {
    await client.query("SELECT set_config($1, $2, false)", [
      `storecalc.${setting}`,
      value,
    ]);
  }
}

async function runAsRole(client, role, callback) {
  await client.query(`SET ROLE ${quoteIdentifier(role)}`);
  try {
    return await callback();
  } finally {
    await resetRole(client);
  }
}

async function runMigrationSql(client, sql) {
  return runAsRole(client, ROLE_SETTINGS.migration_owner_role, async () => {
    await configureRoles(client);
    return client.query(sql);
  });
}

async function removeTestState(client) {
  await resetRole(client);
  await client.query("DROP SCHEMA IF EXISTS storecalc CASCADE");
  await client.query("DROP TABLE IF EXISTS public.users CASCADE");
  for (const role of ALL_TEST_ROLES) {
    await client
      .query(
        `REVOKE CREATE ON DATABASE ${quoteIdentifier(DATABASE_NAME)} FROM ${quoteIdentifier(role)}`,
      )
      .catch(() => null);
  }
  for (const role of [...ALL_TEST_ROLES].reverse()) {
    await client.query(`DROP ROLE IF EXISTS ${quoteIdentifier(role)}`);
  }
}

async function createTestRoles(client) {
  await client.query(
    `REVOKE CREATE ON DATABASE ${quoteIdentifier(DATABASE_NAME)} FROM PUBLIC`,
  );
  for (const role of ALL_TEST_ROLES) {
    await client.query(`
      CREATE ROLE ${quoteIdentifier(role)}
      NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS
    `);
  }
  await client.query(
    `GRANT CREATE ON DATABASE ${quoteIdentifier(DATABASE_NAME)} TO ${quoteIdentifier(ROLE_SETTINGS.migration_owner_role)}`,
  );
}

async function createUsersTable(client) {
  await client.query(`
    CREATE TABLE public.users (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    )
  `);
  await client.query(`
    GRANT REFERENCES (id)
    ON public.users
    TO ${quoteIdentifier(ROLE_SETTINGS.migration_owner_role)}
  `);
}

async function installSchema(client) {
  const migrationSql = new Map(
    MIGRATIONS.map((key) => [
      key,
      {
        up: readFileSync(
          path.join(ROOT, "migrations", "storecalc", key, "up.sql"),
          "utf8",
        ),
        verify: readFileSync(
          path.join(ROOT, "migrations", "storecalc", key, "verify.sql"),
          "utf8",
        ),
      },
    ]),
  );

  await runMigrationSql(client, migrationSql.get(MIGRATIONS[0]).up);
  await runMigrationSql(client, migrationSql.get(MIGRATIONS[0]).verify);
  await createUsersTable(client);
  for (const key of MIGRATIONS.slice(1)) {
    await runMigrationSql(client, migrationSql.get(key).up);
    await runMigrationSql(client, migrationSql.get(key).verify);
  }
}

function createRoleQueryPool(connectionString, role) {
  const pool = new pg.Pool({ connectionString, ssl: false, max: 2 });
  return {
    async query(sql, parameters) {
      const client = await pool.connect();
      try {
        await client.query("RESET ROLE");
        await client.query(`SET ROLE ${quoteIdentifier(role)}`);
        await configureRoles(client);
        return await client.query(sql, parameters);
      } finally {
        await client.query("RESET ROLE").catch(() => null);
        client.release();
      }
    },
    async end() {
      await pool.end();
    },
  };
}

async function insertVersion(client, values) {
  const versionId = (
    await client.query(
      "INSERT INTO storecalc.template_versions (" +
        "template_id, version_number, content_state, currency_code, currency_exponent, " +
        "source_effective_date, source_published_date, calculation_contract_version, " +
        "required_capabilities, content_schema_version, canonicalization_version, " +
        "created_by_subject_id" +
        ") VALUES ($1, $2, 'draft', 'USD', 2, $3, DATE '2026-01-01', " +
        "'storecalc.calculation.v1', $4::text[], 'storecalc.catalog-content.v1', " +
        "'storecalc.canonical-json.v1', $5) RETURNING id",
      [
        values.templateId,
        values.versionNumber,
        values.sourceEffectiveDate,
        REQUIRED_CAPABILITIES,
        values.subjectId,
      ],
    )
  ).rows[0].id;
  const sealed = await client.query(
    "UPDATE storecalc.template_versions " +
      "SET content_state = 'sealed', hash_algorithm = 'sha256', " +
      "content_hash = $2, sealed_at = transaction_timestamp() WHERE id = $1",
    [versionId, values.hashCharacter.repeat(64)],
  );
  assert.equal(sealed.rowCount, 1);
  return versionId;
}

async function insertApplicability(client, values) {
  return (
    await client.query(
      "INSERT INTO storecalc.assignment_template_applicability (" +
        "assignment_id, program_id, facility_id, template_id, selection_mode, " +
        "exact_version_id, publication_id, valid_from, valid_through, " +
        "applicability_state, actor_type, recorded_by_subject_id, reason_code" +
        ") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, " +
        "'owner', $11, 'reviewed_applicability') RETURNING id",
      [
        values.assignmentId,
        values.programId,
        values.facilityId,
        values.templateId,
        values.selectionMode,
        values.exactVersionId ?? null,
        values.publicationId ?? null,
        values.validFrom,
        values.validThrough,
        values.applicabilityState ?? "supported",
        values.subjectId,
      ],
    )
  ).rows[0].id;
}

async function seedFixture(client, userId) {
  return runAsRole(
    client,
    ROLE_SETTINGS.migration_owner_role,
    async () => {
      const subjectId = (
        await client.query(
          "INSERT INTO storecalc.contributor_subjects " +
            "(user_id, status) VALUES ($1, 'active') RETURNING id",
          [userId],
        )
      ).rows[0].id;
      const countryId = (
        await client.query(
          "INSERT INTO storecalc.countries " +
            "(code_alpha2, code_alpha3, official_name, support_status, active) " +
            "VALUES ('US', 'USA', 'United States', 'limited_directory', true) " +
            "RETURNING id",
        )
      ).rows[0].id;
      const facilities = await client.query(
        "INSERT INTO storecalc.facilities (" +
          "physical_country_id, record_scope, owner_user_id, official_name, status, " +
          "created_by_subject_id" +
          ") VALUES " +
          "($1, 'public', NULL, 'Resolver Exact Facility', 'active', $2), " +
          "($1, 'public', NULL, 'Resolver Publication Facility', 'active', $2), " +
          "($1, 'private', $3, 'Resolver Private Facility', 'active', $2) " +
          "RETURNING id, official_name",
        [countryId, subjectId, userId],
      );
      const facilityByName = Object.fromEntries(
        facilities.rows.map((row) => [row.official_name, row.id]),
      );
      const programs = await client.query(
        "INSERT INTO storecalc.store_programs (" +
          "record_scope, owner_user_id, name, status, created_by_subject_id" +
          ") VALUES " +
          "('public', NULL, 'Resolver Public Program', 'active', $1), " +
          "('private', $2, 'Resolver Private Program', 'active', $1) " +
          "RETURNING id, name",
        [subjectId, userId],
      );
      const programByName = Object.fromEntries(
        programs.rows.map((row) => [row.name, row.id]),
      );
      const publicProgramId = programByName["Resolver Public Program"];
      const privateProgramId = programByName["Resolver Private Program"];
      const assignments = await client.query(
        "INSERT INTO storecalc.program_facility_assignments (" +
          "program_id, facility_id, audience_key, valid_from, valid_through, " +
          "assignment_state" +
          ") VALUES " +
          "($1, $3, 'general', DATE '2026-01-01', DATE '2026-12-31', 'supported'), " +
          "($1, $4, 'general', DATE '2026-01-01', DATE '2026-12-31', 'supported'), " +
          "($2, $5, 'general', DATE '2026-01-01', DATE '2026-12-31', 'supported') " +
          "RETURNING id, program_id, facility_id",
        [
          publicProgramId,
          privateProgramId,
          facilityByName["Resolver Exact Facility"],
          facilityByName["Resolver Publication Facility"],
          facilityByName["Resolver Private Facility"],
        ],
      );
      const assignmentFor = (programId, facilityId) =>
        assignments.rows.find(
          (row) =>
            row.program_id === programId && row.facility_id === facilityId,
        ).id;
      const exactAssignmentId = assignmentFor(
        publicProgramId,
        facilityByName["Resolver Exact Facility"],
      );
      const publicationAssignmentId = assignmentFor(
        publicProgramId,
        facilityByName["Resolver Publication Facility"],
      );
      const privateAssignmentId = assignmentFor(
        privateProgramId,
        facilityByName["Resolver Private Facility"],
      );

      const templateNames = [
        "Exact Template",
        "Publication Template",
        "Future Template",
        "Disputed Template",
        "Closed Template",
        "Inactive Template",
      ];
      const publicTemplates = await client.query(
        "INSERT INTO storecalc.templates (" +
          "program_id, visibility, owner_user_id, name, status, created_by_subject_id" +
          ") SELECT $1, 'public', NULL, name, 'active', $2 " +
          "FROM unnest($3::text[]) AS template_name(name) RETURNING id, name",
        [publicProgramId, subjectId, templateNames],
      );
      const privateTemplate = await client.query(
        "INSERT INTO storecalc.templates (" +
          "program_id, visibility, owner_user_id, name, status, created_by_subject_id" +
          ") VALUES ($1, 'private', $2, 'Private Template', 'active', $3) " +
          "RETURNING id, name",
        [privateProgramId, userId, subjectId],
      );
      const templateByName = Object.fromEntries(
        [...publicTemplates.rows, ...privateTemplate.rows].map((row) => [
          row.name,
          row.id,
        ]),
      );

      const version = async (
        templateName,
        versionNumber,
        sourceEffectiveDate,
        hashCharacter,
      ) =>
        insertVersion(client, {
          templateId: templateByName[templateName],
          versionNumber,
          sourceEffectiveDate,
          hashCharacter,
          subjectId,
        });
      const exactVersionId = await version(
        "Exact Template",
        1,
        "2026-06-01",
        "a",
      );
      const publicationVersionOneId = await version(
        "Publication Template",
        1,
        "2026-01-01",
        "b",
      );
      const publicationVersionTwoId = await version(
        "Publication Template",
        2,
        "2026-07-01",
        "c",
      );
      const futureVersionId = await version(
        "Future Template",
        1,
        "2026-07-01",
        "d",
      );
      const disputedVersionId = await version(
        "Disputed Template",
        1,
        "2026-01-01",
        "e",
      );
      const closedVersionId = await version(
        "Closed Template",
        1,
        "2026-01-01",
        "f",
      );
      const inactiveVersionId = await version(
        "Inactive Template",
        1,
        "2026-01-01",
        "1",
      );
      const privateVersionId = await version(
        "Private Template",
        1,
        "2026-01-01",
        "2",
      );

      const publicationOneId = (
        await client.query(
          "INSERT INTO storecalc.template_publications (" +
            "template_id, version_id, actor_type, published_by_subject_id, reason_code" +
            ") VALUES ($1, $2, 'owner', $3, 'reviewed_publication') RETURNING id",
          [
            templateByName["Publication Template"],
            publicationVersionOneId,
            subjectId,
          ],
        )
      ).rows[0].id;
      await new Promise((resolve) => setTimeout(resolve, 5));
      await client.query(
        "UPDATE storecalc.template_publications " +
          "SET ended_at = transaction_timestamp(), ended_actor_type = 'owner', " +
          "ended_by_subject_id = $2, ended_reason_code = 'reviewed_replacement', " +
          "lifecycle_generation = lifecycle_generation + 1 WHERE id = $1",
        [publicationOneId, subjectId],
      );
      const publicationTwoId = (
        await client.query(
          "INSERT INTO storecalc.template_publications (" +
            "template_id, version_id, actor_type, published_by_subject_id, reason_code" +
            ") VALUES ($1, $2, 'owner', $3, 'reviewed_publication') RETURNING id",
          [
            templateByName["Publication Template"],
            publicationVersionTwoId,
            subjectId,
          ],
        )
      ).rows[0].id;

      const common = {
        programId: publicProgramId,
        facilityId: facilityByName["Resolver Exact Facility"],
        assignmentId: exactAssignmentId,
        validFrom: "2026-01-01",
        validThrough: "2026-12-31",
        selectionMode: "exact_version",
        subjectId,
      };
      const exactApplicabilityId = await insertApplicability(client, {
        ...common,
        templateId: templateByName["Exact Template"],
        exactVersionId,
        validFrom: "2026-06-01",
        validThrough: "2026-06-30",
      });
      await insertApplicability(client, {
        programId: publicProgramId,
        facilityId: facilityByName["Resolver Publication Facility"],
        assignmentId: publicationAssignmentId,
        templateId: templateByName["Publication Template"],
        selectionMode: "publication",
        publicationId: publicationOneId,
        validFrom: "2026-01-01",
        validThrough: "2026-12-31",
        subjectId,
      });
      await insertApplicability(client, {
        ...common,
        templateId: templateByName["Future Template"],
        exactVersionId: futureVersionId,
      });
      await insertApplicability(client, {
        ...common,
        templateId: templateByName["Disputed Template"],
        exactVersionId: disputedVersionId,
        applicabilityState: "disputed",
      });
      const closedApplicabilityId = await insertApplicability(client, {
        ...common,
        templateId: templateByName["Closed Template"],
        exactVersionId: closedVersionId,
      });
      await new Promise((resolve) => setTimeout(resolve, 5));
      await client.query(
        "UPDATE storecalc.assignment_template_applicability " +
          "SET ended_at = transaction_timestamp(), ended_actor_type = 'owner', " +
          "ended_by_subject_id = $2, ended_reason_code = 'reviewed_correction', " +
          "lifecycle_generation = lifecycle_generation + 1 WHERE id = $1",
        [closedApplicabilityId, subjectId],
      );
      await insertApplicability(client, {
        ...common,
        templateId: templateByName["Inactive Template"],
        exactVersionId: inactiveVersionId,
      });
      await client.query(
        "UPDATE storecalc.templates SET status = 'inactive', updated_at = transaction_timestamp() " +
          "WHERE id = $1",
        [templateByName["Inactive Template"]],
      );
      await insertApplicability(client, {
        programId: privateProgramId,
        facilityId: facilityByName["Resolver Private Facility"],
        assignmentId: privateAssignmentId,
        templateId: templateByName["Private Template"],
        selectionMode: "exact_version",
        exactVersionId: privateVersionId,
        validFrom: "2026-01-01",
        validThrough: "2026-12-31",
        subjectId,
      });

      return {
        subjectId,
        facilityByName,
        publicProgramId,
        privateProgramId,
        exactAssignmentId,
        templateByName,
        exactVersionId,
        exactApplicabilityId,
        publicationVersionOneId,
        publicationVersionTwoId,
        publicationOneId,
        publicationTwoId,
      };
    },
  );
}

function input(fixture, overrides = {}) {
  return {
    facilityId: fixture.facilityByName["Resolver Exact Facility"],
    programId: fixture.publicProgramId,
    templateId: fixture.templateByName["Exact Template"],
    audienceKey: "general",
    contextDate: "2026-06-15",
    ...overrides,
  };
}

async function expectResolutionError(action, code) {
  await assert.rejects(action, (error) => {
    assert.ok(error instanceof StoreCalcCatalogResolutionError);
    assert.equal(error.code, code);
    return true;
  });
}

test(
  "StoreCalc resolves exact public catalog lineage from native PostgreSQL and fails closed",
  { timeout: 120_000 },
  async () => {
    const connectionString = assertDisposableTarget();
    const client = new pg.Client({ connectionString, ssl: false });
    await client.connect();
    const migrationPool = createRoleQueryPool(
      connectionString,
      ROLE_SETTINGS.migration_owner_role,
    );
    const webPool = createRoleQueryPool(
      connectionString,
      ROLE_SETTINGS.web_role,
    );

    try {
      await removeTestState(client);
      await createTestRoles(client);
      const serverVersion = await client.query("SHOW server_version_num");
      assert.ok(Number(serverVersion.rows[0].server_version_num) >= 170000);
      await installSchema(client);
      const userId = (
        await client.query("INSERT INTO public.users DEFAULT VALUES RETURNING id")
      ).rows[0].id;
      const fixture = await seedFixture(client, userId);

      for (const contextDate of ["2026-06-01", "2026-06-30"]) {
        const resolved = await resolvePublicCatalogVersion(
          migrationPool,
          input(fixture, { contextDate }),
        );
        assert.equal(resolved.state, "resolved");
        assert.equal(resolved.lineage.assignmentId, fixture.exactAssignmentId);
        assert.equal(
          resolved.lineage.applicabilityId,
          fixture.exactApplicabilityId,
        );
        assert.equal(resolved.lineage.selectionMode, "exact_version");
        assert.equal(resolved.lineage.versionId, fixture.exactVersionId);
        assert.equal(resolved.catalog.contentHash, "a".repeat(64));
        assert.equal(resolved.catalog.sourceEffectiveDate, "2026-06-01");
        assert.deepEqual(resolved.assignmentInterval, {
          validFrom: "2026-01-01",
          validThrough: "2026-12-31",
        });
        assert.deepEqual(resolved.applicabilityInterval, {
          validFrom: "2026-06-01",
          validThrough: "2026-06-30",
        });
      }

      for (const contextDate of ["2026-05-31", "2026-07-01"]) {
        assert.equal(
          (
            await resolvePublicCatalogVersion(
              migrationPool,
              input(fixture, { contextDate }),
            )
          ).state,
          "unavailable",
        );
      }

      const publication = await resolvePublicCatalogVersion(
        migrationPool,
        input(fixture, {
          facilityId:
            fixture.facilityByName["Resolver Publication Facility"],
          templateId: fixture.templateByName["Publication Template"],
        }),
      );
      assert.equal(publication.state, "resolved");
      assert.equal(publication.lineage.selectionMode, "publication");
      assert.equal(publication.lineage.publicationId, fixture.publicationOneId);
      assert.equal(publication.lineage.publicationIsCurrent, false);
      assert.equal(
        publication.lineage.versionId,
        fixture.publicationVersionOneId,
      );
      assert.notEqual(
        publication.lineage.versionId,
        fixture.publicationVersionTwoId,
      );
      assert.equal(publication.catalog.contentHash, "b".repeat(64));

      for (const [templateName, overrides] of [
        ["Future Template", {}],
        ["Disputed Template", {}],
        ["Closed Template", {}],
        ["Inactive Template", {}],
        [
          "Private Template",
          {
            facilityId: fixture.facilityByName["Resolver Private Facility"],
            programId: fixture.privateProgramId,
          },
        ],
      ]) {
        assert.equal(
          (
            await resolvePublicCatalogVersion(
              migrationPool,
              input(fixture, {
                templateId: fixture.templateByName[templateName],
                ...overrides,
              }),
            )
          ).state,
          "unavailable",
          `${templateName} unexpectedly resolved`,
        );
      }

      assert.equal(
        (
          await resolvePublicCatalogVersion(
            migrationPool,
            input(fixture, { audienceKey: "wrong_audience" }),
          )
        ).state,
        "unavailable",
      );
      await assert.rejects(
        () => resolvePublicCatalogVersion(webPool, input(fixture)),
        (error) => error.code === "42501",
      );

      await runAsRole(
        client,
        ROLE_SETTINGS.migration_owner_role,
        async () => {
          await client.query(
            "ALTER TABLE storecalc.assignment_template_applicability " +
              "DISABLE TRIGGER assignment_template_applicability_coherence_trigger",
          );
          try {
            const hostileId = (
              await client.query(
                "INSERT INTO storecalc.assignment_template_applicability (" +
                  "assignment_id, program_id, facility_id, template_id, selection_mode, " +
                  "exact_version_id, valid_from, valid_through, applicability_state, " +
                  "actor_type, recorded_by_subject_id, reason_code" +
                  ") VALUES ($1, $2, $3, $4, 'exact_version', $5, " +
                  "DATE '2026-06-01', DATE '2026-06-30', 'supported', " +
                  "'owner', $6, 'hostile_drift') RETURNING id",
                [
                  fixture.exactAssignmentId,
                  fixture.publicProgramId,
                  fixture.facilityByName["Resolver Exact Facility"],
                  fixture.templateByName["Exact Template"],
                  fixture.exactVersionId,
                  fixture.subjectId,
                ],
              )
            ).rows[0].id;
            await expectResolutionError(
              () => resolvePublicCatalogVersion(migrationPool, input(fixture)),
              "CATALOG_RESOLUTION_AMBIGUOUS",
            );
            await client.query(
              "DELETE FROM storecalc.assignment_template_applicability WHERE id = $1",
              [hostileId],
            );
          } finally {
            await client.query(
              "ALTER TABLE storecalc.assignment_template_applicability " +
                "ENABLE TRIGGER assignment_template_applicability_coherence_trigger",
            );
          }
        },
      );

      await runAsRole(
        client,
        ROLE_SETTINGS.migration_owner_role,
        async () => {
          await client.query(
            "UPDATE storecalc.schema_capabilities " +
              "SET schema_version = 10, migration_key = 'future_test_schema' " +
              "WHERE capability_key = 'anonymous.calculation'",
          );
        },
      );
      await expectResolutionError(
        () => resolvePublicCatalogVersion(migrationPool, input(fixture)),
        "SCHEMA_CAPABILITY_UNSUPPORTED",
      );
      await runAsRole(
        client,
        ROLE_SETTINGS.migration_owner_role,
        async () => {
          await client.query(
            "UPDATE storecalc.schema_capabilities " +
              "SET schema_version = 9, " +
              "migration_key = '0012_catalog_publication_applicability' " +
              "WHERE capability_key = 'anonymous.calculation'",
          );
        },
      );
      assert.equal(
        (await resolvePublicCatalogVersion(migrationPool, input(fixture))).state,
        "resolved",
      );
    } finally {
      await migrationPool.end();
      await webPool.end();
      await removeTestState(client);
      await client.end();
    }
  },
);
