import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { fileURLToPath } from "node:url";
import path from "node:path";
import pg from "pg";

import {
  loadSealedCatalogVersionContent,
  sealCatalogVersion,
  StoreCalcCatalogSealingError,
} from "../src/storecalc/catalog/sealingService.js";
import {
  buildSyntheticCatalogContent,
  buildUnsealedSyntheticCatalogContent,
} from "../test/fixtures/storecalc-catalog-content-fixture.js";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const DATABASE_NAME = "storecalc_migration_test";
const ROLE_SETTINGS = {
  migration_owner_role: "storecalc_test_migration",
  web_role: "storecalc_test_web",
  worker_role: "storecalc_test_worker",
  backup_role: "storecalc_test_backup",
};
const OUTSIDER_ROLE = "storecalc_test_outsider";
const ALL_TEST_ROLES = [...Object.values(ROLE_SETTINGS), OUTSIDER_ROLE];
const MIGRATIONS = [
  "0001_schema_foundation",
  "0002_directory_lineage",
  "0003_program_assignments",
  "0004_template_identity",
  "0005_template_versions",
  "0006_version_content",
  "0007_buckets",
  "0008_tax_rules",
  "0009_constraints",
  "0010_warnings",
  "0011_source_evidence",
];
const GOLDEN_HASH =
  "1226f26de7c3e80dbc4cd2fbf2c2f2b30bea5055a0d66e14a821a705e2ea1d44";

function quoteIdentifier(value) {
  assert.match(value, /^[a-z][a-z0-9_]*$/);
  return `"${value}"`;
}

function assertDisposableTarget() {
  assert.equal(
    process.env.STORECALC_DB_TEST_ALLOW,
    "1",
    "STORECALC_DB_TEST_ALLOW=1 is required",
  );
  const connectionString = process.env.STORECALC_TEST_DATABASE_URL;
  assert.ok(connectionString, "STORECALC_TEST_DATABASE_URL is required");
  const target = new URL(connectionString);
  assert.ok(
    ["127.0.0.1", "localhost", "::1"].includes(target.hostname),
    "database tests may target only loopback",
  );
  assert.equal(target.pathname, `/${DATABASE_NAME}`);
  return connectionString;
}

async function resetRole(client) {
  await client.query("ROLLBACK").catch(() => null);
  await client.query("RESET ROLE").catch(() => null);
}

async function configureRoles(client) {
  for (const [setting, value] of Object.entries(ROLE_SETTINGS)) {
    await client.query("SELECT set_config($1, $2, false)", [
      `storecalc.${setting}`,
      value,
    ]);
  }
}

async function runAsRole(client, role, callback) {
  await client.query(`SET ROLE ${quoteIdentifier(role)}`);
  try {
    return await callback();
  } finally {
    await resetRole(client);
  }
}

async function runMigrationSql(client, sql) {
  return runAsRole(client, ROLE_SETTINGS.migration_owner_role, async () => {
    await configureRoles(client);
    return client.query(sql);
  });
}

async function removeTestState(client) {
  await resetRole(client);
  await client.query("DROP SCHEMA IF EXISTS storecalc CASCADE");
  await client.query("DROP TABLE IF EXISTS public.users CASCADE");
  for (const role of ALL_TEST_ROLES) {
    await client
      .query(
        `REVOKE CREATE ON DATABASE ${quoteIdentifier(DATABASE_NAME)} FROM ${quoteIdentifier(role)}`,
      )
      .catch(() => null);
  }
  for (const role of [...ALL_TEST_ROLES].reverse()) {
    await client.query(`DROP ROLE IF EXISTS ${quoteIdentifier(role)}`);
  }
}

async function createTestRoles(client) {
  await client.query(
    `REVOKE CREATE ON DATABASE ${quoteIdentifier(DATABASE_NAME)} FROM PUBLIC`,
  );
  for (const role of ALL_TEST_ROLES) {
    await client.query(`
      CREATE ROLE ${quoteIdentifier(role)}
      NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS
    `);
  }
  await client.query(
    `GRANT CREATE ON DATABASE ${quoteIdentifier(DATABASE_NAME)} TO ${quoteIdentifier(ROLE_SETTINGS.migration_owner_role)}`,
  );
}

async function createUsersTable(client) {
  await client.query(`
    CREATE TABLE public.users (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    )
  `);
  await client.query(`
    GRANT REFERENCES (id)
    ON public.users
    TO ${quoteIdentifier(ROLE_SETTINGS.migration_owner_role)}
  `);
}

async function installSchema(client) {
  const migrationSql = new Map(
    MIGRATIONS.map((key) => [
      key,
      {
        up: readFileSync(
          path.join(ROOT, "migrations", "storecalc", key, "up.sql"),
          "utf8",
        ),
        verify: readFileSync(
          path.join(ROOT, "migrations", "storecalc", key, "verify.sql"),
          "utf8",
        ),
      },
    ]),
  );

  await runMigrationSql(client, migrationSql.get(MIGRATIONS[0]).up);
  await runMigrationSql(client, migrationSql.get(MIGRATIONS[0]).verify);
  await createUsersTable(client);
  for (const key of MIGRATIONS.slice(1)) {
    await runMigrationSql(client, migrationSql.get(key).up);
    await runMigrationSql(client, migrationSql.get(key).verify);
  }
}

function createRolePool(connectionString, role) {
  const pool = new pg.Pool({
    connectionString,
    ssl: false,
    max: 2,
  });
  return {
    async connect() {
      const client = await pool.connect();
      try {
        await client.query("RESET ROLE");
        await client.query(`SET ROLE ${quoteIdentifier(role)}`);
        await configureRoles(client);
        return client;
      } catch (error) {
        client.release();
        throw error;
      }
    },
    async end() {
      await pool.end();
    },
  };
}

async function openMigrationClient(connectionString) {
  const client = new pg.Client({ connectionString, ssl: false });
  await client.connect();
  await client.query(
    `SET ROLE ${quoteIdentifier(ROLE_SETTINGS.migration_owner_role)}`,
  );
  await configureRoles(client);
  return client;
}

async function createTemplateFixture(client, content) {
  const userId = (
    await client.query("INSERT INTO public.users DEFAULT VALUES RETURNING id")
  ).rows[0].id;
  return runAsRole(client, ROLE_SETTINGS.migration_owner_role, async () => {
    const subjectId = (
      await client.query(
        "INSERT INTO storecalc.contributor_subjects " +
          "(user_id, status) VALUES ($1, 'active') RETURNING id",
        [userId],
      )
    ).rows[0].id;
    const programId = (
      await client.query(
        "INSERT INTO storecalc.store_programs (" +
          "record_scope, owner_user_id, name, status, created_by_subject_id" +
          ") VALUES ('public', NULL, 'Catalog Seal Test Program', 'active', $1) " +
          "RETURNING id",
        [subjectId],
      )
    ).rows[0].id;
    const templateId = (
      await client.query(
        "INSERT INTO storecalc.templates (" +
          "program_id, visibility, owner_user_id, name, status, created_by_subject_id" +
          ") VALUES ($1, 'public', NULL, 'Catalog Seal Test Template', 'active', $2) " +
          "RETURNING id",
        [programId, subjectId],
      )
    ).rows[0].id;

    const categoryIds = new Map();
    for (const category of content.categories) {
      const categoryId = (
        await client.query(
          "INSERT INTO storecalc.template_categories " +
            "(template_id, stable_key, created_by_subject_id) " +
            "VALUES ($1, $2, $3) RETURNING id",
          [templateId, category.categoryKey, subjectId],
        )
      ).rows[0].id;
      categoryIds.set(category.categoryKey, categoryId);
    }

    const itemIds = new Map();
    for (const item of content.items) {
      const itemId = (
        await client.query(
          "INSERT INTO storecalc.template_items " +
            "(template_id, stable_key, created_by_subject_id) " +
            "VALUES ($1, $2, $3) RETURNING id",
          [templateId, item.itemKey, subjectId],
        )
      ).rows[0].id;
      itemIds.set(item.itemKey, itemId);
    }

    return { subjectId, programId, templateId, categoryIds, itemIds };
  });
}

async function createEvidenceFixture(client, content, subjectId) {
  return runAsRole(client, ROLE_SETTINGS.migration_owner_role, async () => {
    const evidenceIds = new Map();
    const sourceGroupIds = new Map();
    for (const [index, evidence] of content.sourceEvidence.entries()) {
      const evidenceId = (
        await client.query(
          "INSERT INTO storecalc.evidence (" +
            "contributor_subject_id, source_type, source_url, source_title, " +
            "source_date, language_tag, metadata_visibility, privacy_state, " +
            "redistribution_state, normalized_fingerprint" +
            ") VALUES ($1, 'external_citation', $2, $3, $4, 'en-US', " +
            "'public_citation', 'metadata_safe', 'metadata_only', $5) RETURNING id",
          [
            subjectId,
            `https://example.invalid/catalog-${index + 1}`,
            `Synthetic catalog source ${index + 1}`,
            content.sourcePublishedDate,
            evidence.evidenceFingerprint,
          ],
        )
      ).rows[0].id;
      const sourceGroupId = (
        await client.query(
          "INSERT INTO storecalc.evidence_groups (" +
            "grouping_type, canonical_fingerprint, independence_state" +
            ") VALUES ('source_lineage', $1, 'accepted') RETURNING id",
          [evidence.sourceGroupFingerprint],
        )
      ).rows[0].id;
      evidenceIds.set(evidence.evidenceFingerprint, evidenceId);
      sourceGroupIds.set(evidence.sourceGroupFingerprint, sourceGroupId);
    }
    return { evidenceIds, sourceGroupIds };
  });
}

async function insertVersionHeader(
  client,
  fixture,
  content,
  versionNumber,
) {
  return (
    await client.query(
      "INSERT INTO storecalc.template_versions (" +
        "template_id, version_number, content_state, currency_code, currency_exponent, " +
        "source_effective_date, source_published_date, calculation_contract_version, " +
        "required_capabilities, content_schema_version, canonicalization_version, " +
        "created_by_subject_id" +
        ") VALUES ($1, $2, 'draft', $3, $4, $5, $6, $7, $8::text[], $9, $10, $11) " +
        "RETURNING id",
      [
        fixture.templateId,
        versionNumber,
        content.currencyCode,
        content.currencyExponent,
        content.sourceEffectiveDate,
        content.sourcePublishedDate,
        content.calculationContractVersion,
        content.requiredCapabilities,
        content.contentSchemaVersion,
        content.canonicalizationVersion,
        fixture.subjectId,
      ],
    )
  ).rows[0].id;
}

async function insertVersionContent(
  client,
  fixture,
  evidenceFixture,
  content,
  versionId,
  { includeEvidence = true } = {},
) {
  const categoryVersionIds = new Map();
  for (const category of content.categories) {
    const id = (
      await client.query(
        "INSERT INTO storecalc.version_categories (" +
          "version_id, template_id, category_id, display_name, description, sort_order, active" +
          ") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id",
        [
          versionId,
          fixture.templateId,
          fixture.categoryIds.get(category.categoryKey),
          category.displayName,
          category.description,
          category.sortOrder,
          category.active,
        ],
      )
    ).rows[0].id;
    categoryVersionIds.set(category.categoryKey, id);
  }

  const itemVersionIds = new Map();
  for (const item of content.items) {
    const id = (
      await client.query(
        "INSERT INTO storecalc.version_items (" +
          "version_id, template_id, item_id, category_version_id, sku, display_name, " +
          "description, unit_label, price_state, price_minor, minimum_selected_quantity, " +
          "maximum_order_quantity, quantity_step, availability_state, sort_order" +
          ") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) " +
          "RETURNING id",
        [
          versionId,
          fixture.templateId,
          fixture.itemIds.get(item.itemKey),
          item.categoryKey === null
            ? null
            : categoryVersionIds.get(item.categoryKey),
          item.sku,
          item.displayName,
          item.description,
          item.unitLabel,
          item.priceState,
          item.priceMinor,
          item.minimumSelectedQuantity,
          item.maximumOrderQuantity,
          item.quantityStep,
          item.availabilityState,
          item.sortOrder,
        ],
      )
    ).rows[0].id;
    itemVersionIds.set(item.itemKey, id);
  }

  const bucketIds = new Map();
  for (const bucket of content.spendingBuckets) {
    const id = (
      await client.query(
        "INSERT INTO storecalc.version_spending_buckets (" +
          "version_id, stable_key, display_name, limit_state, limit_minor, " +
          "measure_currency_code, is_primary_display, sort_order" +
          ") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id",
        [
          versionId,
          bucket.bucketKey,
          bucket.displayName,
          bucket.limitState,
          bucket.limitMinor,
          bucket.measureCurrencyCode,
          bucket.isPrimaryDisplay,
          bucket.sortOrder,
        ],
      )
    ).rows[0].id;
    bucketIds.set(bucket.bucketKey, id);
  }

  for (const membership of content.bucketMemberships) {
    await client.query(
      "INSERT INTO storecalc.version_item_bucket_memberships (" +
        "version_item_id, version_id, spending_bucket_id, membership_type, primary_display" +
        ") VALUES ($1, $2, $3, $4, $5)",
      [
        itemVersionIds.get(membership.itemKey),
        versionId,
        bucketIds.get(membership.bucketKey),
        membership.membershipType,
        membership.primaryDisplay,
      ],
    );
  }

  for (const rule of content.taxRules) {
    await client.query(
      "INSERT INTO storecalc.version_tax_rules (" +
        "version_id, scope_type, category_version_id, item_version_id, treatment_state, " +
        "rate_ppm, price_includes_tax, rounding_mode, rounding_scope, priority" +
        ") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)",
      [
        versionId,
        rule.scopeType,
        rule.categoryKey === null
          ? null
          : categoryVersionIds.get(rule.categoryKey),
        rule.itemKey === null ? null : itemVersionIds.get(rule.itemKey),
        rule.treatmentState,
        rule.ratePpm,
        rule.priceIncludesTax,
        rule.roundingMode,
        rule.roundingScope,
        rule.priority,
      ],
    );
  }

  for (const constraint of content.constraints) {
    await client.query(
      "INSERT INTO storecalc.version_constraints (" +
        "version_id, stable_key, display_name, constraint_type, measure_type, comparator, " +
        "value_state, limit_value, unit_code, scope_type, composition_behavior, priority" +
        ") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)",
      [
        versionId,
        constraint.constraintKey,
        constraint.displayName,
        constraint.constraintType,
        constraint.measureType,
        constraint.comparator,
        constraint.valueState,
        constraint.limitValue,
        constraint.unitCode,
        constraint.scopeType,
        constraint.compositionBehavior,
        constraint.priority,
      ],
    );
  }

  for (const warning of content.warnings) {
    await client.query(
      "INSERT INTO storecalc.version_warnings (" +
        "version_id, warning_code, severity, scope_type, category_version_id, " +
        "item_version_id, message_key, bounded_details" +
        ") VALUES ($1, $2, $3, $4, NULL, $5, $6, $7::jsonb)",
      [
        versionId,
        warning.warningCode,
        warning.severity,
        warning.scopeType,
        warning.itemKey === null ? null : itemVersionIds.get(warning.itemKey),
        warning.messageKey,
        JSON.stringify(warning.boundedDetails),
      ],
    );
  }

  if (includeEvidence) {
    for (const evidence of content.sourceEvidence) {
      await client.query(
        "INSERT INTO storecalc.version_source_evidence (" +
          "version_id, evidence_id, relationship_type, source_group_id" +
          ") VALUES ($1, $2, $3, $4)",
        [
          versionId,
          evidenceFixture.evidenceIds.get(evidence.evidenceFingerprint),
          evidence.relationshipType,
          evidenceFixture.sourceGroupIds.get(
            evidence.sourceGroupFingerprint,
          ),
        ],
      );
    }
  }
  return { categoryVersionIds, itemVersionIds, bucketIds };
}

async function seedVersion(
  client,
  fixture,
  evidenceFixture,
  content,
  versionNumber,
  options = {},
) {
  return runAsRole(client, ROLE_SETTINGS.migration_owner_role, async () => {
    const versionId = await insertVersionHeader(
      client,
      fixture,
      content,
      versionNumber,
    );
    const rowIds = await insertVersionContent(
      client,
      fixture,
      evidenceFixture,
      content,
      versionId,
      options,
    );
    return { versionId, ...rowIds };
  });
}

async function expectSealingError(action, code) {
  await assert.rejects(action, (error) => {
    assert.ok(error instanceof StoreCalcCatalogSealingError);
    assert.equal(error.code, code);
    return true;
  });
}

async function waitForTopologyLock(client) {
  for (let attempt = 0; attempt < 100; attempt += 1) {
    const result = await client.query(`
      SELECT count(*)::integer AS lock_count
      FROM pg_locks
      WHERE relation = 'storecalc.template_versions'::regclass
        AND mode = 'ShareRowExclusiveLock'
        AND granted
    `);
    if (result.rows[0].lock_count > 0) return;
    await new Promise((resolve) => setTimeout(resolve, 20));
  }
  assert.fail("catalog sealing never acquired the topology lock");
}

test(
  "StoreCalc database sealing and exact sealed loading are canonical, serialized, fail-closed, and runtime-isolated",
  { timeout: 90_000 },
  async () => {
    const connectionString = assertDisposableTarget();
    const client = new pg.Client({ connectionString, ssl: false });
    await client.connect();
    const migrationPool = createRolePool(
      connectionString,
      ROLE_SETTINGS.migration_owner_role,
    );
    const webPool = createRolePool(connectionString, ROLE_SETTINGS.web_role);

    try {
      await removeTestState(client);
      await createTestRoles(client);
      const serverVersion = await client.query("SHOW server_version_num");
      assert.ok(Number(serverVersion.rows[0].server_version_num) >= 170000);
      await installSchema(client);

      const unsealed = buildUnsealedSyntheticCatalogContent();
      const expected = buildSyntheticCatalogContent();
      const fixture = await createTemplateFixture(client, unsealed);
      const evidenceFixture = await createEvidenceFixture(
        client,
        unsealed,
        fixture.subjectId,
      );

      const first = await seedVersion(
        client,
        fixture,
        evidenceFixture,
        unsealed,
        1,
      );
      const sealed = await sealCatalogVersion(migrationPool, {
        versionId: first.versionId,
      });
      assert.equal(sealed.contentHash, GOLDEN_HASH);
      assert.deepEqual(sealed.catalog, expected);
      assert.deepEqual(
        (
          await client.query(
            "SELECT content_state, hash_algorithm, content_hash, sealed_at IS NOT NULL AS has_sealed_at " +
              "FROM storecalc.template_versions WHERE id = $1",
            [first.versionId],
          )
        ).rows,
        [
          {
            content_state: "sealed",
            hash_algorithm: "sha256",
            content_hash: GOLDEN_HASH,
            has_sealed_at: true,
          },
        ],
      );
      await expectSealingError(
        () =>
          sealCatalogVersion(migrationPool, { versionId: first.versionId }),
        "VERSION_NOT_DRAFT",
      );
      await runAsRole(client, ROLE_SETTINGS.migration_owner_role, async () => {
        await assert.rejects(
          client.query(
            "UPDATE storecalc.version_items SET display_name = 'Rewritten' " +
              "WHERE version_id = $1",
            [first.versionId],
          ),
          /storecalc_sealed_version_content_immutable/,
        );
      });

      const second = await seedVersion(
        client,
        fixture,
        evidenceFixture,
        unsealed,
        2,
      );
      const mutationClient = await openMigrationClient(connectionString);
      try {
        await mutationClient.query("BEGIN");
        await mutationClient.query(
          "UPDATE storecalc.version_items " +
            "SET display_name = 'Committed before sealing' " +
            "WHERE id = $1",
          [second.itemVersionIds.get("sample_soup")],
        );

        let sealSettled = false;
        const concurrentSeal = sealCatalogVersion(migrationPool, {
          versionId: second.versionId,
        }).finally(() => {
          sealSettled = true;
        });
        await new Promise((resolve) => setTimeout(resolve, 100));
        assert.equal(
          sealSettled,
          false,
          "catalog sealing bypassed an in-flight topology mutation",
        );
        await mutationClient.query("COMMIT");
        const afterMutation = await concurrentSeal;
        assert.equal(
          afterMutation.catalog.items.find(
            (item) => item.itemKey === "sample_soup",
          ).displayName,
          "Committed before sealing",
        );
        assert.notEqual(afterMutation.contentHash, GOLDEN_HASH);
      } finally {
        await resetRole(mutationClient);
        await mutationClient.end();
      }

      const third = await seedVersion(
        client,
        fixture,
        evidenceFixture,
        unsealed,
        3,
        { includeEvidence: false },
      );
      await runAsRole(client, ROLE_SETTINGS.migration_owner_role, async () => {
        const pendingEvidenceId = (
          await client.query(
            "INSERT INTO storecalc.evidence (" +
              "contributor_subject_id, source_type, source_url, source_title, " +
              "metadata_visibility, privacy_state, redistribution_state, normalized_fingerprint" +
              ") VALUES ($1, 'external_citation', 'https://example.invalid/pending', " +
              "'Pending source', 'private', 'pending_review', 'metadata_only', $2) " +
              "RETURNING id",
            [fixture.subjectId, "3".repeat(64)],
          )
        ).rows[0].id;
        await client.query(
          "ALTER TABLE storecalc.version_source_evidence DISABLE TRIGGER " +
            "version_source_evidence_eligibility_trigger",
        );
        try {
          await client.query(
            "INSERT INTO storecalc.version_source_evidence (" +
              "version_id, evidence_id, relationship_type, source_group_id" +
              ") VALUES ($1, $2, 'supports_catalog', $3)",
            [
              third.versionId,
              pendingEvidenceId,
              evidenceFixture.sourceGroupIds.get("2".repeat(64)),
            ],
          );
        } finally {
          await client.query(
            "ALTER TABLE storecalc.version_source_evidence ENABLE TRIGGER " +
              "version_source_evidence_eligibility_trigger",
          );
        }
      });
      await expectSealingError(
        () =>
          sealCatalogVersion(migrationPool, { versionId: third.versionId }),
        "SOURCE_EVIDENCE_INELIGIBLE",
      );
      assert.deepEqual(
        (
          await client.query(
            "SELECT content_state, content_hash FROM storecalc.template_versions WHERE id = $1",
            [third.versionId],
          )
        ).rows,
        [{ content_state: "draft", content_hash: null }],
      );

      const fourth = await seedVersion(
        client,
        fixture,
        evidenceFixture,
        unsealed,
        4,
      );
      await assert.rejects(
        () => sealCatalogVersion(webPool, { versionId: fourth.versionId }),
        (error) => error.code === "42501",
      );
      assert.deepEqual(
        (
          await client.query(
            "SELECT content_state, content_hash FROM storecalc.template_versions WHERE id = $1",
            [fourth.versionId],
          )
        ).rows,
        [{ content_state: "draft", content_hash: null }],
      );

      const fifth = await seedVersion(
        client,
        fixture,
        evidenceFixture,
        unsealed,
        5,
      );
      const headerBlocker = await openMigrationClient(connectionString);
      const blockedMutation = await openMigrationClient(connectionString);
      try {
        await headerBlocker.query("BEGIN");
        await headerBlocker.query(
          "SELECT id FROM storecalc.template_versions WHERE id = $1 FOR UPDATE",
          [fifth.versionId],
        );
        const sealHoldingTopology = sealCatalogVersion(migrationPool, {
          versionId: fifth.versionId,
        });
        await waitForTopologyLock(client);

        let mutationSettled = false;
        const mutationAfterSealStarted = blockedMutation
          .query(
            "UPDATE storecalc.version_items SET display_name = 'Too late' " +
              "WHERE id = $1",
            [fifth.itemVersionIds.get("sample_soup")],
          )
          .finally(() => {
            mutationSettled = true;
          });
        const mutationRejection = assert.rejects(
          mutationAfterSealStarted,
          /storecalc_sealed_version_content_immutable/,
        );
        await new Promise((resolve) => setTimeout(resolve, 100));
        assert.equal(
          mutationSettled,
          false,
          "content mutation bypassed an active sealing topology lock",
        );
        await headerBlocker.query("COMMIT");
        await sealHoldingTopology;
        await mutationRejection;
      } finally {
        await resetRole(headerBlocker);
        await resetRole(blockedMutation);
        await headerBlocker.end();
        await blockedMutation.end();
      }

      const sixth = await seedVersion(
        client,
        fixture,
        evidenceFixture,
        unsealed,
        6,
      );
      const competingSeals = await Promise.allSettled([
        sealCatalogVersion(migrationPool, { versionId: sixth.versionId }),
        sealCatalogVersion(migrationPool, { versionId: sixth.versionId }),
      ]);
      assert.equal(
        competingSeals.filter((result) => result.status === "fulfilled").length,
        1,
      );
      const rejectedSeal = competingSeals.find(
        (result) => result.status === "rejected",
      );
      assert.ok(rejectedSeal.reason instanceof StoreCalcCatalogSealingError);
      assert.equal(rejectedSeal.reason.code, "VERSION_NOT_DRAFT");

      await runMigrationSql(
        client,
        readFileSync(
          path.join(
            ROOT,
            "migrations",
            "storecalc",
            "0011_source_evidence",
            "verify.sql",
          ),
          "utf8",
        ),
      );

      for (const filename of ["up.sql", "verify.sql"]) {
        await runMigrationSql(
          client,
          readFileSync(
            path.join(
              ROOT,
              "migrations",
              "storecalc",
              "0012_catalog_publication_applicability",
              filename,
            ),
            "utf8",
          ),
        );
      }

      const loaded = await loadSealedCatalogVersionContent(migrationPool, {
        versionId: first.versionId,
        templateId: fixture.templateId,
        contentHash: GOLDEN_HASH,
      });
      assert.equal(loaded.versionId, first.versionId);
      assert.equal(loaded.templateId, fixture.templateId);
      assert.equal(loaded.contentHash, GOLDEN_HASH);
      assert.deepEqual(loaded.catalog, expected);
      await expectSealingError(
        () =>
          loadSealedCatalogVersionContent(migrationPool, {
            versionId: first.versionId,
            templateId: fixture.templateId,
            contentHash: "0".repeat(64),
          }),
        "VERSION_SEALED_HASH_STATE_INVALID",
      );
      await assert.rejects(
        () =>
          loadSealedCatalogVersionContent(webPool, {
            versionId: first.versionId,
            templateId: fixture.templateId,
            contentHash: GOLDEN_HASH,
          }),
        (error) => error.code === "42501",
      );
    } finally {
      await migrationPool.end().catch(() => null);
      await webPool.end().catch(() => null);
      await removeTestState(client).catch(() => null);
      await client.end();
    }
  },
);
